### ISSUE TITLE
<Ctrl>` shortcut doesn't work

### ISSUE THREAD

**Issue by Loreno10** [CristianHenzel/ClipIt#169] opened 2021-01-20 18:31 UTC
I tried setting up \<Ctrl\>\` as a shortcut for history view. It just doesn't work.

**Comment by MandySimbuka** [comment] 2021-02-02 12:35
@Loreno10 You can't only use `<Ctrl>` since it is a modifier, you can however use something like `<Ctrl>H`

**Comment by OhMyMndy** [comment] 2021-02-02 12:36
@Loreno10 You can't only use `<Ctrl>` since it is a modifier, you can however use something like `<Ctrl>H`

**Comment by Loreno10** [comment] 2021-02-02 15:19
I’m not using only CTRL. There is CTRL and a back tick.

**Comment by OhMyMndy** [comment] 2021-02-04 15:58
I tried to use `<Ctrl>``, ran `clipit` from the command line and it core dumped when pressing that key combination...

**Comment by CristianHenzel** [comment] 2021-02-04 21:03
Duplicate of #70 70

**Closed by CristianHenzel** 2021-02-04 21:03 UTC
