### ISSUE TITLE
Clipit keyboard shortcuts not working + Preferences problem

### ISSUE THREAD

**Issue by jazbina** [CristianHenzel/ClipIt#101] opened 2018-08-12 13:10 UTC
Not a single shortcut works.
I get this when I start Clipit from terminal.
`** (clipit:11659): WARNING **: 14:54:21.514: Binding '<Ctrl><Alt>A' failed!

** (clipit:11659): WARNING **: 14:54:21.514: Binding '<Ctrl><Alt>P' failed!

** (clipit:11659): WARNING **: 14:54:21.514: Binding '<Ctrl><Alt>F' failed!

** (clipit:11659): WARNING **: 14:54:21.514: Binding '<Ctrl><Alt>O' failed!

(clipit:11659): Gdk-CRITICAL **: 14:54:21.718: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
`

 Also I cant see Preferences content when I open it. It just opens blank window. 

I am on
> System:
  Host: debian Kernel: 4.17.0-1-amd64 x86_64 bits: 64 Desktop: Xfce 4.12.4 
  Distro: Debian GNU/Linux buster/sid 

Clipit 1.4.4-2

I reinstalled Clipit but that did not help.

**Comment by cortopy** [comment] 2018-08-19 18:08
Same experience after upgrading to latest version. When I try to use a keybinding the terminal outputs:

```
(clipit:6815): GLib-GObject-CRITICAL **: 19:07:21.561: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by cortopy** [comment] 2018-08-19 18:09
actually this is a duplicate of https://github.com/CristianHenzel/ClipIt/issues/97

**Closed** 2019-11-26 11:39 UTC
